

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      - CI_ENVIRONMENT=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=codeigniter

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=codeigniter
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3307"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=db           
      - PMA_USER=root         
      - PMA_PASSWORD=root     
    restart: always